#theme: jekyll-theme-minimal
remote_theme: pmarsceill/just-the-docs
search_enabled: true
aux_links:
    "Issues / Knowledge Base":
      - "https://github.com/Stadicus/RaspiBolt/issues"
    "Contribute! Source on GitHub":
      - "https://github.com/Stadicus/RaspiBolt/"

# enable theme for local usage
#theme: "just-the-docs"
